DATA PROCESSING TOOL

IMPORTING LIBRARIES

In [37]:
 import pandas as pd
 import numpy as np
 import matplotlib.pyplot as plt

IMPORTING DATASET

In [38]:
dataset = pd.read_csv('data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [39]:
print(x)

[['USA' 26.0 57462.0]
 ['India' 38.0 47192.0]
 ['Germany' 40.0 46094.0]
 ['USA' 29.0 44574.0]
 ['India' 26.0 59066.0]
 ['Germany' 39.0 48778.0]
 ['USA' 28.0 44027.0]
 ['India' 28.0 55163.0]
 ['Germany' 36.0 51701.0]]


In [40]:
print(y)

['Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'Yes' 'Yes']


TAKING CARE OF MISSING DATA

In [41]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
imputer.transform(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])


In [42]:
print(x)

[['USA' 26.0 57462.0]
 ['India' 38.0 47192.0]
 ['Germany' 40.0 46094.0]
 ['USA' 29.0 44574.0]
 ['India' 26.0 59066.0]
 ['Germany' 39.0 48778.0]
 ['USA' 28.0 44027.0]
 ['India' 28.0 55163.0]
 ['Germany' 36.0 51701.0]]


ENCODING CATEGORICAL DATA

ENCODING THE INDEPDENT VARIABLE

In [43]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(
    transformers=[
        ('encoder', OneHotEncoder(), [0])  # apply OneHotEncoder to column 0 (the Country column)
    ],
    remainder='passthrough',  # keep other columns (age and salary) as they are
)

x = np.array(ct.fit_transform(x))


In [44]:
print(x)

[[0.0 0.0 1.0 26.0 57462.0]
 [0.0 1.0 0.0 38.0 47192.0]
 [1.0 0.0 0.0 40.0 46094.0]
 [0.0 0.0 1.0 29.0 44574.0]
 [0.0 1.0 0.0 26.0 59066.0]
 [1.0 0.0 0.0 39.0 48778.0]
 [0.0 0.0 1.0 28.0 44027.0]
 [0.0 1.0 0.0 28.0 55163.0]
 [1.0 0.0 0.0 36.0 51701.0]]


ENCODING THE DEPENDENT VARIABLE

In [45]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [46]:
print(y)

[1 0 1 0 1 0 1 1 1]


SPLITTING THE DATASET INTO TRAINING SET AND TEST SET

In [47]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [48]:
print(x_train)

[[0.0 0.0 1.0 28.0 44027.0]
 [0.0 1.0 0.0 28.0 55163.0]
 [0.0 1.0 0.0 38.0 47192.0]
 [0.0 0.0 1.0 26.0 57462.0]
 [0.0 1.0 0.0 26.0 59066.0]
 [0.0 0.0 1.0 29.0 44574.0]
 [1.0 0.0 0.0 39.0 48778.0]]


In [49]:
print(x_test)

[[1.0 0.0 0.0 36.0 51701.0]
 [1.0 0.0 0.0 40.0 46094.0]]


In [50]:
print(y_train)

[1 1 0 1 1 0 0]


In [51]:
print(y_test)

[1 1]


FEATURE SCALING

In [52]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])





In [53]:
print(x_train)

[[0.0 0.0 1.0 -0.5019402478798447 -1.1892648959773862]
 [0.0 1.0 0.0 -0.5019402478798447 0.7391684693467921]
 [0.0 1.0 0.0 1.4500496049862168 -0.6411783656926319]
 [0.0 0.0 1.0 -0.8923382184530569 1.1372888273640591]
 [0.0 1.0 0.0 -0.8923382184530569 1.4150552711481812]
 [0.0 0.0 1.0 -0.30674126259323853 -1.0945403044874145]
 [1.0 0.0 0.0 1.6452485902728229 -0.3665290017015986]]


In [54]:
print(x_test)

[[1.0 0.0 0.0 1.0596516344130045 0.13965012247607503]
 [1.0 0.0 0.0 1.840447575559429 -0.8313202330710395]]
