NATURAL LANGUAGE PROCESSING

IMPORTING LIBRARIES

In [64]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

IMPORTING DATASETS

In [65]:
dataset = pd.read_csv('Restaurant_Reviews.csv', quoting=3, on_bad_lines='skip')
x = dataset.iloc[:, 0].values
y = dataset.iloc[:, 1].values

print(dataset.columns)
display(dataset.head())

Index(['Review', 'Liked'], dtype='object')


Review  Liked
0                           Wow... Loved this place.      1
1                                 Crust is not good.      0
2          Not tasty and the texture was just nasty.      0
3  Stopped by during the late May bank holiday of...      1
4  The selection on the menu was great and so wer...      1

CLEANING THE TEXTS

In [66]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []

for i in range(0, len(dataset)):
  reviews = re.sub('[^a-zA-Z]', ' ', dataset['Review'][i])
  reviews = reviews.lower()
  reviews = reviews.split()
  ps = PorterStemmer()
  all_stopwords = stopwords.words('english')
  all_stopwords.remove('not')
  reviews = [ps.stem(word) for word in reviews if word not in (all_stopwords)]
  reviews = ' '.join(reviews)
  corpus.append(reviews)



for review in corpus:
    print(review, '\n')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


wow love place 

crust not good 

not tasti textur nasti 

stop late may bank holiday rick steve recommend love 

select menu great price 

get angri want damn pho 

honeslti tast fresh 

potato like rubber could tell made ahead time kept warmer 

fri great 

great touch 

servic prompt 

would not go back 

cashier care ever say still end wayyy overpr 

disgust pretti sure human hair 

shock sign indic cash 

highli recommend 

waitress littl slow servic 

not like 

burritto blah 

servic also cute 

could care less interior beauti 

perform 

right red velvet cake ohhh stuff good 

never brought salad ask 

worst salmon sashimi 

like final blow 

found place accid could not happier 

redeem qualiti restaur inexpens 

ampl portion good price 

first visit hiro delight 

servic suck 

shrimp tender moist 

not deal good enough would drag establish 

hard judg whether side good gross melt styrofoam want eat fear get sick 

thing like prime rib dessert section 

bad food damn gener 

w

CREATING THE BAG OF WORDS MODEL

In [67]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
x = cv.fit_transform(corpus).toarray()
y = dataset.iloc[:, -1].values

print(len(x[0]))

print(x)
print('\n\n',y)

1144
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


 [1 0 0 1 1 0 0 0 1 1 1 0 0 0 0 1 0 0 0 1 1 1 1 0 0 0 1 1 1 1 0 1 0 0 1 0 1
 1 1 1 1 0 0 0 1 1 1 1 1 1 0 1 0 0 0 1 1 0 0 0 0 1 0 1 0 1 1 1 1 0 0 1 1 0
 1 1 1 1 1 1 1 1 0 0 0 0 1 0 0 0 1 0 1 1 1 0 0 0 0 1 1 0 0 1 1 0 0 1 1 1 1
 1 0 1 0 1 1 1 0 0 1 1 1 0 0 0 0 0 1 1 1 1 1 0 1 0 0 1 1 1 0 1 1 1 0 0 0 1
 0 1 1 0 1 0 1 0 0 1 1 1 1 1 1 1 0 0 1 0 0 0 1 1 0 1 0 1 1 1 1 0 1 0 1 1 1
 1 1 1 1 1 1 1 0 0 1 0 0 1 1 0 0 1 0 0 1 0 1 0 1 1 0 0 0 1 0 1 1 0 1 0 0 1
 0 1 1 1 1 0 0 0 1 1 0 0 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 0 1 0 1 1 0 0
 0 1 0 0 0 1 1 0 0 0 1 0 0 1 1 1 1 0 1 1 1 0 0 1 0 1 1 1 0 1 1 0 0 0 1 1 1
 0 0 1 1 0 1 0 1 1 0 1 0 1 1 1 0 1 0 1 0 0 1 0 1 0 0 0 0 1 1 1 0 1 1 0 1 1
 0 1 0 1 0 1 1 1 1 0 0 0 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1 0 0 0 0 0 1 1 1 1 0
 1 0 1 0 1 1 1 1 0 1 0 0 1 1 0 1 0 1 1 0 1 1 1 0 0 0 1 1 0 0 1 1 1 0 1 0 0
 0 0 0 1 0 1 1 0 0 1 0 1 0 0 1 1 1 0 0 1 0 1 1 

SPLITTING THE DATASET INTO TRAINING SET AND TEST SET

In [68]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

TRAINING THE NAVIE BAYES MODEL ON THE TRAINING SET

In [69]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(x_train, y_train)

GaussianNB()

PREDICTING THE TEST SET RESULT

In [70]:
y_predict = classifier.predict(x_test)
print(np.concatenate((y_predict.reshape(len(y_predict), 1), y_test.reshape(len(y_test), 1)), 1))

[[0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [1 0]
 [0 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [1 0]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [1 0]
 [0 0]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 0]
 [1 1]
 [0 1]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [0 1]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [0 0]
 [0 0]
 [1 0]
 [0 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [1 1]]


MAKING THE CONFUSION MATRIX

In [71]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
cm = confusion_matrix(y_test, y_predict)
print(cm)
accuracy_score(y_test, y_predict)

[[40 27]
 [ 6 69]]


0.7676056338028169