IMPORTING LIBRARIES

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

IMPORTING DATASET

In [2]:
dataset = pd.read_csv('Social_Network_Ads.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

print(x)
print(y)

[[    19  19000]
 [    35  20000]
 [    26  43000]
 [    27  57000]
 [    19  76000]
 [    27  58000]
 [    27  84000]
 [    32 150000]
 [    25  33000]
 [    35  65000]
 [    26  80000]
 [    26  52000]
 [    20  86000]
 [    32  18000]
 [    18  82000]
 [    29  80000]
 [    47  25000]
 [    45  26000]
 [    46  28000]
 [    48  29000]
 [    45  22000]
 [    47  49000]
 [    48  41000]
 [    45  22000]
 [    46  23000]
 [    47  20000]
 [    49  28000]
 [    47  30000]
 [    29  43000]
 [    31  18000]
 [    31  74000]
 [    27 137000]
 [    21  16000]
 [    28  44000]
 [    27  90000]
 [    35  27000]
 [    33  28000]
 [    30  49000]
 [    26  72000]
 [    27  31000]
 [    27  17000]
 [    33  51000]
 [    35 108000]
 [    30  15000]
 [    28  84000]
 [    23  20000]
 [    25  79000]
 [    27  54000]
 [    30 135000]
 [    31  89000]
 [    24  32000]
 [    18  44000]
 [    29  83000]
 [    35  23000]
 [    27  58000]
 [    24  55000]
 [    23  48000]
 [    28  79000]
 [    22  1800

SPLITTING THE DATASET INTO TRAINING SET AND TESTING SET

In [3]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)

FEATURE SCALING

In [4]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)


print(x_train)
print(x_test)

[[-0.13296151 -0.49669234]
 [-0.61543109  1.4707241 ]
 [ 1.02496546  2.07830859]
 [-0.61543109  0.89207221]
 [ 0.92847155  2.07830859]
 [ 1.41094112  1.00780259]
 [ 0.06002631 -0.78601828]
 [-0.0364676  -0.23629898]
 [ 0.15652023 -0.64135531]
 [ 0.34950806  0.11089215]
 [-0.32594934 -1.27787239]
 [-0.32594934 -0.55455753]
 [ 0.44600197  1.23926335]
 [ 0.83197763 -0.58349012]
 [ 1.98990461 -1.16214202]
 [ 0.15652023  0.25555513]
 [-0.32594934  0.22662253]
 [-0.711925    0.57381367]
 [ 1.41094112  2.13617378]
 [ 0.83197763 -0.52562493]
 [-1.19439458 -1.56719834]
 [-0.32594934 -0.26523158]
 [ 0.73548372  0.28448772]
 [ 1.02496546  0.48701588]
 [-0.32594934  0.28448772]
 [-0.80841892  0.57381367]
 [ 0.92847155 -0.81495088]
 [-0.13296151  2.22297157]
 [-0.0364676   1.26819594]
 [-0.90491283 -0.64135531]
 [ 0.25301414 -0.6992205 ]
 [ 2.08639853 -0.78601828]
 [-1.38738241 -1.45146796]
 [-0.0364676  -0.29416417]
 [ 1.98990461  2.13617378]
 [-1.00140675 -0.29416417]
 [-0.0364676  -0.55455753]
 

TRAINING THE SVM MODEL ON TRAINING SET

In [5]:
from sklearn import svm
classifier = svm.SVC(kernel = 'linear', random_state = 0)
classifier.fit(x_train, y_train)

SVC(kernel='linear', random_state=0)

PREDICTING NEW RESULTS

In [6]:
age = 30
salary = 87000
print(classifier.predict(sc.transform([[age, salary]])))

[0]


PREDICTING TEST RESULTS

In [7]:
y_pred = classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]]


MAKING THE CONFUSION MATRIX

In [8]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[66  7]
 [ 6 21]]


0.87

VISUALISING THE TRAINING SET RESULTS

In [ ]:
from matplotlib.colors import ListedColormap
x_set, y_set = sc.inverse_transform(x_train), y_train
X1, X2 = np.meshgrid(np.arange(start = x_set[:, 0].min() - 10, stop = x_set[:, 0].max() + 10, step = 0.25),
                     np.arange(start = x_set[:, 1].min() - 1000, stop = x_set[:, 1].max() + 1000, step = 0.25))
plt.contourf(X1, X2, classifier.predict(sc.transform(np.array([X1.ravel(), X2.ravel()]).T)).reshape(X1.shape),
             alpha = 0.75, cmap = ListedColormap(('red', 'green')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)):
    plt.scatter(x_set[y_set == j, 0], x_set[y_set == j, 1], c = ListedColormap(('red', 'green'))(i), label = j)
plt.title('logistic regression (training set)')
plt.xlabel('age')
plt.ylabel('estimated salary')
plt.legend()
plt.show()

